CREATE TABLE `mymodule_not_index` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `TITLE` VARCHAR(255) NOT NULL,
        `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
    );

CREATE TABLE `mymodule_index` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NOT NULL,
  `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(ID),
  INDEX `ix_created` (`CREATED`)
);